require:
  - rubocop-rails
  - rubocop-rspec

Metrics/LineLength:
  Max: 130
  AutoCorrect: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: '#english-comments'
  Enabled: true
  VersionAdded: '0.9'
  VersionChanged: '0.52'
  AllowedChars: ["á", "â", "ã", "ä", "å", "æ", "ç", "è", "é", "ê", "ë", "ì", "í", "î", "ï", "ð", "ñ", "ò", "ó", "ô", "õ", "ö", "ø", "ù", "ú"]

ClassAndModuleChildren:
  Enabled: false

Convention:Rails/HasAndBelongsToMany:
  Enabled: false

convention:RSpec/ExampleLength:
  Enabled: false

convention:RSpec/MultipleMemoizedHelpers:
  Enabled: false

convention:Style/DoubleNegation:
  Enabled: false

convention:Style/MixinGrouping:
  Enabled: false

convention:Rails/SkipsModelValidations:
  Enabled: false

convention:RSpec/ImplicitExpect:
  EnforcedStyle: should

convention:RSpec/LetSetup:
  Enabled: false

convention:RSpec/EmptyLineAfterExample:
  Enabled: false

convention:Style/MultilineIfModifier:
  Enabled: false

convention:Style/HashAsLastArrayItem:
  Enabled: false

convention:Layout/ArgumentAlignment:
  Enabled: false
